### ISSUE TITLE
chamtool.py errors while executing CONFIG=?

### ISSUE THREAD

**Issue by hsanjuan** [emsec/ChameleonMini#16]
```
$> python3 chamtool.py -p /dev/ttyACM0 -v
[2016-10-08 13:38:47.531460] Opening serial port /dev/ttyACM0 succeeded
[2016-10-08 13:38:47.532812] Executing <VERSION?>: 101:OK WITH TEXT
[2016-10-08 13:38:47.533115] Response: ChameleonMini RevG 161008 using LUFA 151115 compiled with AVR-GCC 4.8.3
[2016-10-08 13:38:47.533382] Executing <CONFIG=?>: Based on the open-source NFC tool ChameleonMini
Traceback (most recent call last):
  File "chamtool.py", line 205, in <module>
    main()
  File "chamtool.py", line 168, in main
    if (chameleon.connect(args.port)):
  File "/multimedia/git/ChameleonMini/Software/Chameleon/Device.py", line 96, in connect
    result = self.getCmdSuggestions(self.COMMAND_CONFIG)
  File "/multimedia/git/ChameleonMini/Software/Chameleon/Device.py", line 168, in getCmdSuggestions
    result = self.getSetCmd(cmd, self.SUGGEST_CHAR)
  File "/multimedia/git/ChameleonMini/Software/Chameleon/Device.py", line 165, in getSetCmd
    return self.writeCmd("{}{}{}".format(cmd, self.SET_CHAR, arg))
  File "/multimedia/git/ChameleonMini/Software/Chameleon/Device.py", line 134, in writeCmd
    statusCode, statusText = status.split(":")
ValueError: need more than 1 value to unpack
```

**Comment by hsanjuan** [comment]
It's because VERSION? gives a multiline response and only the first line of it is processed

**Comment by timokasper** [comment]
ah thanks for this feedback, we have added 3 lines just yesterday so hasn't been tested yet --> we will fix it.
 
TK


 
Von: Hector Sanjuan [mailto:notifications@github.com] 
Gesendet: Samstag, 8. Oktober 2016 15:58
An: emsec/ChameleonMini <ChameleonMini@noreply.github.com>
Betreff: Re: [emsec/ChameleonMini] chamtool.py errors while executing CONFIG=? (#16)
 
It's because VERSION? gives a multiline response and only the first line of it is processed

**Comment by geo-rg** [comment]
Please verify if #25 - which is merged now - solves the problem for you.

**Comment by hsanjuan** [comment]
It does solve the problem. THANKS!
