### ISSUE TITLE
chamtool.py ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by scaery** [emsec/ChameleonMini#36]
Any help? I am using latest Kali and the sources you proposed here on github...

python3 chamtool.py -p /dev/ttyACM0 -i

`Traceback (most recent call last):
  File "chamtool.py", line 205, in <module>
    main()
  File "chamtool.py", line 168, in main
    if (chameleon.connect(args.port)):
  File "/usr/local/src/pentest-rfid/ChameleonMini/Software/Chameleon/Device.py", line 96, in connect
    result = self.getCmdSuggestions(self.COMMAND_CONFIG)
  File "/usr/local/src/pentest-rfid/ChameleonMini/Software/Chameleon/Device.py", line 168, in getCmdSuggestions
    result = self.getSetCmd(cmd, self.SUGGEST_CHAR)
  File "/usr/local/src/pentest-rfid/ChameleonMini/Software/Chameleon/Device.py", line 165, in getSetCmd
    return self.writeCmd("{}{}{}".format(cmd, self.SET_CHAR, arg))
  File "/usr/local/src/pentest-rfid/ChameleonMini/Software/Chameleon/Device.py", line 134, in writeCmd
    statusCode, statusText = status.split(":")
ValueError: not enough values to unpack (expected 2, got 1)`

However, socat - /dev/ttyACM0,crnl works. Are patches around or am i using it wrong, there`s not really much help inside...

**Comment by scaery** [comment]
fixed by issue #16 https://github.com/emsec/ChameleonMini/pull/19/commits/8ece4f783ab79680ac1ab094b8863cf90b7bc655

> closed
